---
version: 2.1

orbs:
  image: twdps/image-provenance@dev:<<pipeline.git.revision>>
  op: twdps/onepassword@2.0.2
  do: twdps/pipeline-events@3.0.0

globals:
  - &context orb-publishing

jobs:

  test commands:
    docker:
      - image: twdps/circleci-executor-builder:alpine-stable
    steps:
      - checkout
      - setup_remote_docker
      - op/env:
          env-file: op.env
      - do/set-docker-credentials
      - op/write:
          op-value: empc-lab/svc-cosign-private-key/notesPlain
          out-file: cosign.key
      - op/write:
          op-value: empc-lab/svc-cosign-public-key/notesPlain
          out-file: cosign.pub
      - run:
          name: build an OCI image text fixture
          command: |
            docker build -t docker.io/twdps/orb-image-provenance:dev.${CIRCLE_SHA1:0:7} -f test/Dockerfile .
            docker push docker.io/twdps/orb-image-provenance:dev.${CIRCLE_SHA1:0:7}
      - image/sign:
          registry: docker.io
          image: twdps/orb-image-provenance
          tag: dev.${CIRCLE_SHA1:0:7}
          sbom: true

  test machine packages:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - image/packages:
          cosign-version: 2.0.1
          syft-version: 0.76.1
          oras-version: 1.0.0

workflows:

  integration tests:
    jobs:
      - test commands:
          context: *context
      - test machine packages
