---
version: 2.1

orbs:
  image: twdps/image-provenance@dev:<<pipeline.git.revision>>
  op: twdps/onepassword@2.0.2

globals:
  - &context orb-publishing

commands:

  set-environment:
    steps:
      - op/env:
          env-file: op.env

  echo-message:
    parameters:
      msg:
        type: string
    steps:
      - run:
          name: echo msg
          command: echo "<< parameters.msg >>"

jobs:

  # test commands:
  #   docker:
  #     - image: twdps/circleci-executor-builder:alpine-stable
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - set-environment
  #     - executor-tools/lint:
  #         dockerfile: test/Dockerfile.alpine
  #         hadolint-additional-args: "--ignore DL3004"
  #     - executor-tools/confirm-registry
  #     - executor-tools/cis-scan:
  #         dockerfile: test/Dockerfile.alpine
  #     - executor-tools/build:
  #         dockerfile: test/Dockerfile.build
  #         image: twdps/orb-executor-tools
  #     - executor-tools/snyk-scan:
  #           image: twdps/orb-executor-tools
  #           tag: dev.${CIRCLE_SHA1:0:7}
  #           dockerfile: test/Dockerfile.build
  #           snyk-severity-threshold: medium
  #           snyk-organization: twdps
  #     - executor-tools/trivy-scan:
  #           image: twdps/orb-executor-tools
  #           tag: dev.${CIRCLE_SHA1:0:7}
  #           dockerfile: test/Dockerfile.build
  #     - executor-tools/grype-scan:
  #           image: twdps/orb-executor-tools
  #           tag: dev.${CIRCLE_SHA1:0:7}
  #           dockerfile: test/Dockerfile.build
  #     - executor-tools/bats:
  #           image: twdps/orb-executor-tools
  #           tag: dev.${CIRCLE_SHA1:0:7}
  #           bats-run-container-name: orb-executor-tools-test
  #           bats-entry-point: /bin/ash
  #           bats-test-path: test/circleci_remote_docker_alpine.bats

  test machine packages:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - image/packages:
          cosign-version: 2.0.1
          syft-version: 0.76.1
          oras-version: 1.0.0
      - run:
          name: confirm installed version for available packages
          command: |
            set -exo pipefail
            cosign version | grep "2.0.1"
            syft version | grep "1.76.1"
            oras version | grep "1.0.0"

workflows:

  integration tests:
    jobs:
      # - test commands:
      #     context: *context

      - test machine packages
